# Generated by Django 2.1.5 on 2019-02-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funds',
            options={'verbose_name_plural': 'Funds'},
        ),
    ]
